#!/bin/bash


N=""
minsize="1c"
human_readable=false
directories=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -N)
            N="$2"
            shift 2
            ;;
        -s)
            minsize="$2"
            shift 2
            ;;
        -h)
            human_readable=true
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Неизвестная опция: $1"
            exit 1
            ;;
        *)
            directories+=("$1")
            shift
            ;;
    esac
done

if [ ${#directories[@]} -eq 0 ]; then
    directories=(".")
fi

find_cmd="find ${directories[@]} -type f -size +$minsize -print0"

if $human_readable; then
    eval $find_cmd | xargs -0 ls -lh | sort -rh -k5 | head -n ${N:-0} | awk '{print $5, $9}'
else
    eval $find_cmd | xargs -0 ls -l | sort -rn -k5 | head -n ${N:-0} | awk '{print $5, $9}'
fi
